# 测试配置文件
# @author <a href="https://github.com/aiaicoder">程序员小新</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456

  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
    # Redis 配置
    # todo 需替换配置
  data:
    redis:
      database: 1
      port: 6379
      host: localhost
      timeout: 5000
      password: 123456

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true